import { Inter } from "next/font/google";
import Head from "next/head";
import { Navbar } from "../Navbar";
import styles from "./MainLayout.module.css";
import { ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children: ReactElement | ReactElement[]
}

export const MainLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Intro Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={`${styles.main} ${inter.className}`}>{children}</main>
    </>
  );
};
